### ISSUE TITLE
Navbar of MyCourt

### ISSUE THREAD

**Issue by Alexander-Schulte** [Alexander-Schulte/Capstone-MyCourt#1]
## Value Statement

As a user of "MyCourt"
I want to implement a navbar at the bottom of every page. It should be easy to use and to see.

## Description
![Bildschirmfoto 2021-04-26 um 12 48 34](https://user-images.githubusercontent.com/79858009/116071097-b90a6d80-a68d-11eb-910c-adc58cd33276.png)

## Acceptance Criteria

- In the navbar should be four icons, so the user can navigate between every page
- The icons should be SVG from the Adobe XD file
- The icons should be specific so the user knows to which page he navigates
- It should be fixed at the bottom of the pages

## Tasks

- [x] Add the home icon which links to the landing page
- [x] Add the map icon which links to the map page
- [x] Add the list icon which links to the list page
- [x] Add the add icon which links to the add court page
## Complexity

Small
