### ISSUE TITLE
Court Map Page:

### ISSUE THREAD

**Issue by Alexander-Schulte** [Alexander-Schulte/Capstone-MyCourt#11]
## Value Statement

As a user of "MyCourt"
I want to implement a "List" page. In here, the user have the option to see all courts in a list with less the important information. If he clicks on a specific court card, it should be collapsible and it shows all information

## Description
<img width="244" alt="Bildschirmfoto 2021-05-03 um 12 36 21" src="https://user-images.githubusercontent.com/79858009/116866805-4a3c8f80-ac0c-11eb-8900-af836c825196.png">
<img width="241" alt="Bildschirmfoto 2021-05-03 um 12 36 47" src="https://user-images.githubusercontent.com/79858009/116866815-4c9ee980-ac0c-11eb-99d3-8fdfc564488a.png">
<img width="241" alt="Bildschirmfoto 2021-05-03 um 12 37 02" src="https://user-images.githubusercontent.com/79858009/116866824-4f014380-ac0c-11eb-902e-c6cd7071afba.png">

## Acceptance Criteria

- The Map should be in the same colors like the background image (looks smooth and nice)
- The map should be scrollable while the user slides 
- The map should show with icons where a specific icon is located
- If the user clicks on the icon the court card should be sliding inside from the right side to show all the information:
    -Name
    -Rating
    -Address
    - Pictures
    -Description
    
- There should be a little delete button so card is hidden again and the user see the whole map again and 
- The user can click on the search button and a search input should pop up:
   the user can now search for a specific location to see all icons/courts there

## Tasks

- [x] The map is scrollable to all directions
- [x] The map should show all specific icons where the courts are located
- [x] The icons should be clickable and show the specific court card
- [x] the delete button on the courdCard removes it and shows the whole map again
- [x] the search icon is clickable so the the user can search/filter for a specific location

## Complexity

Large
