### ISSUE TITLE
Add a court

### ISSUE THREAD

**Issue by Alexander-Schulte** [Alexander-Schulte/Capstone-MyCourt#2]
## Value Statement

As a user of "MyCourt"
I want to implement a "Add court" page. In here, the user have the option to add a new court to the map or list.

## Description
![Bildschirmfoto 2021-04-26 um 13 02 42](https://user-images.githubusercontent.com/79858009/116072661-b1e45f00-a68f-11eb-9e58-aa26ae29890e.png)

## Acceptance Criteria

- The <form> should be very easy to use and don't take so much time to add a new court
- Inputs:
  Name
  Location
  Opening Time
  Description 
- Special eye on the rating: the stars should be filled colour when the user is hover it
- Images should be required to upload
- After you add a new court the user should get a notification that it was add
- It should be easy to upload pictures
- There should be a function that locations (and names?) should only be used once.

## Tasks

- [x] The user can type in the court name
- [x] The user can rate the court
- [x] The user can type in the court location
- [x] The user can type in the opening time
- [x] The user can add pictures
- [x] The user can add a description
- [x] The user can submit the court
- [x] Function that locations and names are only used once

## Complexity

Medium
