### ISSUE TITLE
List all Courts

### ISSUE THREAD

**Issue by Alexander-Schulte** [Alexander-Schulte/Capstone-MyCourt#3]
## Value Statement

As a user of "MyCourt"
I want to implement a "List" page. In here, the user have the option to see all courts in a list with less the important information. If he clicks on a specific court card, it should be collapsible and it shows all information. There should be a search button to filter all the courts for the name and location. 

## Description
<img width="292" alt="Bildschirmfoto 2021-04-26 um 16 03 07" src="https://user-images.githubusercontent.com/79858009/116095676-eb759400-a6a8-11eb-8fdb-0f4ed1457183.png">

<img width="294" alt="Bildschirmfoto 2021-04-26 um 16 03 34" src="https://user-images.githubusercontent.com/79858009/116095727-f7615600-a6a8-11eb-8d15-c15d3776e931.png">

## Acceptance Criteria

- The Court Cards are all the same size
- The page is scrollable
- The Court cards are collapsible, if the clicks on it, it shows all the information:
    -Name
    -Address
    -Description
    -picture

## Tasks

- [x] The page is scrollable
- [x] The Court cards are collapsible
- [x] The full Court card shows all the information
- [x] Filter to search for names and locations

## Complexity

Medium
